In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris
from sklearn.feature_selection import SelectKBest, chi2
from sklearn.feature_selection import RFE 
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import load_wine

/home/ahmad/.local/lib/python3.10/site-packages/matplotlib/projections/__init__.py:63: UserWarning: Unable to import Axes3D. This may be due to multiple versions of Matplotlib being installed (e.g. as a system package and as a pip package). As a result, the 3D projection is not available.
  warnings.warn("Unable to import Axes3D. This may be due to multiple versions of "


In [2]:
data = load_wine()
x, y = data.data, data.target


In [3]:
df = pd.DataFrame(x, columns=data.feature_names)
df['Target'] = y
df

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0      14.23        1.71  2.43               15.6      127.0           2.80   
1      13.20        1.78  2.14               11.2      100.0           2.65   
2      13.16        2.36  2.67               18.6      101.0           2.80   
3      14.37        1.95  2.50               16.8      113.0           3.85   
4      13.24        2.59  2.87               21.0      118.0           2.80   
..       ...         ...   ...                ...        ...            ...   
173    13.71        5.65  2.45               20.5       95.0           1.68   
174    13.40        3.91  2.48               23.0      102.0           1.80   
175    13.27        4.28  2.26               20.0      120.0           1.59   
176    13.17        2.59  2.37               20.0      120.0           1.65   
177    14.13        4.10  2.74               24.5       96.0           2.05   

     flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0          3.06                  0.28             2.29             5.64  1.04   
1          2.76                  0.26             1.28             4.38  1.05   
2          3.24                  0.30             2.81             5.68  1.03   
3          3.49                  0.24             2.18             7.80  0.86   
4          2.69                  0.39             1.82             4.32  1.04   
..          ...                   ...              ...              ...   ...   
173        0.61                  0.52             1.06             7.70  0.64   
174        0.75                  0.43             1.41             7.30  0.70   
175        0.69                  0.43             1.35            10.20  0.59   
176        0.68                  0.53             1.46             9.30  0.60   
177        0.76                  0.56             1.35             9.20  0.61   

     od280/od315_of_diluted_wines  proline  Target  
0                            3.92   1065.0       0  
1                            3.40   1050.0       0  
2                            3.17   1185.0       0  
3                            3.45   1480.0       0  
4                            2.93    735.0       0  
..                            ...      ...     ...  
173                          1.74    740.0       2  
174                          1.56    750.0       2  
175                          1.56    835.0       2  
176                          1.62    840.0       2  
177                          1.60    560.0       2  

[178 rows x 14 columns]

In [4]:
df.describe()

alcohol  malic_acid         ash  alcalinity_of_ash   magnesium  \
count  178.000000  178.000000  178.000000         178.000000  178.000000   
mean    13.000618    2.336348    2.366517          19.494944   99.741573   
std      0.811827    1.117146    0.274344           3.339564   14.282484   
min     11.030000    0.740000    1.360000          10.600000   70.000000   
25%     12.362500    1.602500    2.210000          17.200000   88.000000   
50%     13.050000    1.865000    2.360000          19.500000   98.000000   
75%     13.677500    3.082500    2.557500          21.500000  107.000000   
max     14.830000    5.800000    3.230000          30.000000  162.000000   

       total_phenols  flavanoids  nonflavanoid_phenols  proanthocyanins  \
count     178.000000  178.000000            178.000000       178.000000   
mean        2.295112    2.029270              0.361854         1.590899   
std         0.625851    0.998859              0.124453         0.572359   
min         0.980000    0.340000              0.130000         0.410000   
25%         1.742500    1.205000              0.270000         1.250000   
50%         2.355000    2.135000              0.340000         1.555000   
75%         2.800000    2.875000              0.437500         1.950000   
max         3.880000    5.080000              0.660000         3.580000   

       color_intensity         hue  od280/od315_of_diluted_wines      proline  \
count       178.000000  178.000000                    178.000000   178.000000   
mean          5.058090    0.957449                      2.611685   746.893258   
std           2.318286    0.228572                      0.709990   314.907474   
min           1.280000    0.480000                      1.270000   278.000000   
25%           3.220000    0.782500                      1.937500   500.500000   
50%           4.690000    0.965000                      2.780000   673.500000   
75%           6.200000    1.120000                      3.170000   985.000000   
max          13.000000    1.710000                      4.000000  1680.000000   

           Target  
count  178.000000  
mean     0.938202  
std      0.775035  
min      0.000000  
25%      0.000000  
50%      1.000000  
75%      2.000000  
max      2.000000

In [5]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)
x_train

array([[1.434e+01, 1.680e+00, 2.700e+00, ..., 5.700e-01, 1.960e+00,
        6.600e+02],
       [1.253e+01, 5.510e+00, 2.640e+00, ..., 8.200e-01, 1.690e+00,
        5.150e+02],
       [1.237e+01, 1.070e+00, 2.100e+00, ..., 1.040e+00, 2.770e+00,
        6.600e+02],
       ...,
       [1.438e+01, 1.870e+00, 2.380e+00, ..., 1.200e+00, 3.000e+00,
        1.547e+03],
       [1.269e+01, 1.530e+00, 2.260e+00, ..., 9.600e-01, 2.060e+00,
        4.950e+02],
       [1.234e+01, 2.450e+00, 2.460e+00, ..., 8.000e-01, 3.380e+00,
        4.380e+02]], shape=(142, 13))

# FILTER METHODS

In [6]:
#menggunakan selectKbest 
filter_selector = SelectKBest(score_func= chi2, k=2) #memilih 2 fitur terbaik
x_train_filter = filter_selector.fit_transform(x_train, y_train)
x_test_filter = filter_selector.transform(x_test)

print(f"Jumlah fitur setelah seleksi {x_train_filter.shape[1]}")

#mendapatkan indeks fitur yang terpilih
selected_indeces = filter_selector.get_support(indices=True)
selected_indeces

Jumlah fitur setelah seleksi 2


array([ 9, 12])

In [7]:
#melihat nama fitur  yang terpilih
selected_features = [data.feature_names[i] for i in selected_indeces]
selected_features

['color_intensity', 'proline']

In [8]:
#melihat skor masing-masing fitur

# WRAPPER METHOD

In [9]:
#menggunakan RFE(Recursive  Feature Selection )
model = LogisticRegression(solver='lbfgs', max_iter= 5000)
rfe_selector = RFE(model, n_features_to_select=2)
x_train_rfe = rfe_selector.fit_transform(x_train, y_train)
x_test_rfe = rfe_selector.transform(x_test)

result = rfe_selector.get_support(indices=True)
result

array([0, 6])

# Embedded Methods

In [10]:
rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
rf_model.fit(x_train, y_train)

importance = rf_model.feature_importances_
importance

array([0.11239774, 0.03570276, 0.02128206, 0.03242488, 0.0368407 ,
       0.02927859, 0.20229342, 0.01351525, 0.02356092, 0.17120218,
       0.07089132, 0.11156432, 0.13904587])

In [11]:
indices = np.argsort(importance)[::-1]
indices

array([ 6,  9, 12,  0, 11, 10,  4,  1,  3,  5,  8,  2,  7])

In [12]:
treshold = 0.05
important_feature_indices = [i for i in range(len(importance)) if importance[i] >= treshold]
important_feature_indices

[0, 6, 9, 10, 11, 12]

In [26]:
x_important = x_train[:, important_feature_indices]
x_test_important = x_test[:, important_feature_indices]



In [27]:
#mengecek fitur yang dipilih 
for colum, i in enumerate(important_feature_indices):
    print(f'{data.feature_names[i]} : {importance[i]}')

alcohol : 0.11239773542143086
flavanoids : 0.20229341635663622
color_intensity : 0.1712021830864957
hue : 0.07089132259413944
od280/od315_of_diluted_wines : 0.1115643167260497
proline : 0.13904586955351153


In [28]:
data.feature_names[1]

'malic_acid'

evaluasi fitur dari fitur-fitur yang terpilih

In [29]:
def evaluate_model(x_train, x_test, y_train, y_test, model):
    model.fit(x_train, y_train)
    accuracy = model.score(x_test, y_test)
    return accuracy



In [31]:
#model logistic regression untuk filter methods
logistic_model_filter = LogisticRegression(max_iter=200)
accuracy_filter = evaluate_model(x_train_filter, x_test_filter, y_train, y_test, logistic_model_filter)

#model logistic regression untuk wrapper method
logistic_model_rfe= LogisticRegression(max_iter=200)
accuracy_rfe = evaluate_model(x_train_rfe, x_test_rfe, y_train, y_test, logistic_model_rfe)

#model random forest untuk embeded method
accuracy_rf = evaluate_model(x_important, x_test_important, y_train, y_test, rf_model)

In [36]:
print(f"Akurasi model dengan filter methods : {accuracy_filter:.2f}")
print(f"Akurasi model dengan wrapper method : { accuracy_rfe:.2f}")
print(f"Akurasi model random forest dengan embeded method {accuracy_rf}")

Akurasi model dengan filter methods : 0.89
Akurasi model dengan wrapper method : 0.94
Akurasi model random forest dengan embeded method 1.0
