In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris
from sklearn.feature_selection import SelectKBest, chi2
from sklearn.feature_selection import RFE 
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import load_wine

In [ ]:
data = load_wine()
x, y = data.data, data.target


array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
        1.065e+03],
       [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
        1.050e+03],
       [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
        1.185e+03],
       ...,
       [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
        8.350e+02],
       [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
        8.400e+02],
       [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
        5.600e+02]], shape=(178, 13))

In [18]:
df = pd.DataFrame(x, columns=data.feature_names)
df['Target'] = y
df

alcohol  malic_acid   ash  ...  od280/od315_of_diluted_wines  proline  Target
0      14.23        1.71  2.43  ...                          3.92   1065.0       0
1      13.20        1.78  2.14  ...                          3.40   1050.0       0
2      13.16        2.36  2.67  ...                          3.17   1185.0       0
3      14.37        1.95  2.50  ...                          3.45   1480.0       0
4      13.24        2.59  2.87  ...                          2.93    735.0       0
..       ...         ...   ...  ...                           ...      ...     ...
173    13.71        5.65  2.45  ...                          1.74    740.0       2
174    13.40        3.91  2.48  ...                          1.56    750.0       2
175    13.27        4.28  2.26  ...                          1.56    835.0       2
176    13.17        2.59  2.37  ...                          1.62    840.0       2
177    14.13        4.10  2.74  ...                          1.60    560.0       2

[178 rows x 14 columns]

In [20]:
df.describe()

alcohol  malic_acid  ...      proline      Target
count  178.000000  178.000000  ...   178.000000  178.000000
mean    13.000618    2.336348  ...   746.893258    0.938202
std      0.811827    1.117146  ...   314.907474    0.775035
min     11.030000    0.740000  ...   278.000000    0.000000
25%     12.362500    1.602500  ...   500.500000    0.000000
50%     13.050000    1.865000  ...   673.500000    1.000000
75%     13.677500    3.082500  ...   985.000000    2.000000
max     14.830000    5.800000  ...  1680.000000    2.000000

[8 rows x 14 columns]

In [24]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)
x_train

array([[1.434e+01, 1.680e+00, 2.700e+00, ..., 5.700e-01, 1.960e+00,
        6.600e+02],
       [1.253e+01, 5.510e+00, 2.640e+00, ..., 8.200e-01, 1.690e+00,
        5.150e+02],
       [1.237e+01, 1.070e+00, 2.100e+00, ..., 1.040e+00, 2.770e+00,
        6.600e+02],
       ...,
       [1.438e+01, 1.870e+00, 2.380e+00, ..., 1.200e+00, 3.000e+00,
        1.547e+03],
       [1.269e+01, 1.530e+00, 2.260e+00, ..., 9.600e-01, 2.060e+00,
        4.950e+02],
       [1.234e+01, 2.450e+00, 2.460e+00, ..., 8.000e-01, 3.380e+00,
        4.380e+02]], shape=(142, 13))

# FILTER METHODS

In [ ]:
#menggunakan selectKbest 
filter_selector = SelectKBest(score_func= chi2, k=2) #memilih 2 fitur terbaik
x_train_filter = filter_selector.fit_transform(x_train, y_train)
x_test_filter = filter_selector.transform(x_test)


array([[5.100000e+00, 8.450000e+02],
       [5.240000e+00, 1.080000e+03],
       [4.600000e+00, 6.000000e+02],
       [5.700000e+00, 1.285000e+03],
       [4.680000e+00, 5.100000e+02],
       [6.200000e+00, 1.280000e+03],
       [1.280000e+00, 5.640000e+02],
       [7.300000e+00, 7.500000e+02],
       [2.650000e+00, 6.800000e+02],
       [5.600000e+00, 7.800000e+02],
       [3.520000e+00, 8.450000e+02],
       [8.600000e+00, 5.000000e+02],
       [4.280000e+00, 1.035000e+03],
       [3.400000e+00, 3.720000e+02],
       [7.300000e+00, 1.310000e+03],
       [2.000000e+00, 3.250000e+02],
       [3.080000e+00, 4.340000e+02],
       [2.200000e+00, 6.300000e+02],
       [7.220000e+00, 1.045000e+03],
       [2.900000e+00, 3.850000e+02],
       [8.700000e+00, 1.680000e+03],
       [5.300000e+00, 5.020000e+02],
       [3.270000e+00, 6.800000e+02],
       [8.500000e+00, 6.300000e+02],
       [9.899999e+00, 4.700000e+02],
       [9.580000e+00, 6.150000e+02],
       [2.060000e+00, 3.450000e+02],
 